### ISSUE TITLE
Debug sendgrid webhook for bounces

### ISSUE THREAD

**Issue by gkop** [rails-school/school#139]
I set up this webhook route to automatically unsubscribe bounced emails - https://github.com/rails-school/school/blob/5bc73de05915a823c3f7bff5c704c687b38e1553/config/routes.rb#L41 .

It worked for a while and then randomly stopped working.

I went back and forth with sendgrid support but they were unable to give me a clear answer on what query exactly they thought they were sending out.

Ever since I have been reconciling these bounces manually.

It might be a good idea to resolve this before tackling #138 , since we may decide to switch email vendors if sendgrid's webhooks are really broken.

**Comment by cdale77** [comment]
Fixed with 
https://github.com/rails-school/school/pull/147
https://github.com/rails-school/school/pull/142
https://github.com/rails-school/school/pull/141
https://github.com/rails-school/school/pull/140
