### ISSUE TITLE
Hiding last name in attendance does not work

### ISSUE THREAD

**Issue by acadet** [rails-school/school#153]
I activated this option but my last name is still visible when attending to a class.

**Comment by btaitelb** [comment]
You're marked as an admin, and according to `app/helpers/application_helper.rb` your last name will only be hidden if you have that flag toggled and you're a non-admin user.

**Comment by acadet** [comment]
Gotcha. Well, maybe hide this option for admins then ;)

**Comment by gkop** [comment]
It's confusing. If I understand Ben correctly, the flag does have an effect on admin users, but only when viewed by non-admin users?

**Comment by btaitelb** [comment]
I believe if someone's an admin, their full name will always be shown. Here's the relevant code from `app/helpers/application_helper.rb`:

```
module ApplicationHelper
  def format_user_name(user)
    if user.hide_last_name? && !user.admin?
      user.name.split(" ").first
    else
      user.name
    end
  end
```

I agree it's confusing. While I can see the logic behind wanting admins to show up with their full names for reputation purposes, I could also see a case where an admin doesn't want their full name to show up (maybe they're being harassed or want privacy), so is there any harm in just respecting the flag always?

**Comment by gkop** [comment]
That sounds like a good idea to me Ben.

**Comment by btaitelb** [comment]
I no longer see your last name on the lesson @acadet, so closing.
