### ISSUE TITLE
Hangout url links are not being used as recording links

### ISSUE THREAD

**Issue by cdale77** [rails-school/school#159]
In the lesson model we have a hangout url, and also a lesson recording url. This is OK, but for Google Hangouts on Air, the url is the same. That is, after the hangout users can hit the link to watch it. So we need a callback or something in the controller to use the hangout url as the recording url, if a hangout url is present and a recording url is not.

**Comment by gkop** [comment]
Maybe this is a separate bug, but https://www.railsschool.org/l/ruby-trees has a hangout_url, yet no link is displayed...

**Comment by donaldali** [comment]
@btaitelb do you want to have the hangout show up just 15 minutes before a lesson starts

**Comment by btaitelb** [comment]
So my thinking in https://github.com/rails-school/school/blob/master/app/views/lessons/show.html.haml (which btw is pretty ugly, and should probably be moved to a helper or a partial) was that I often turn open up the hangout on air prior to recording the class, so it's good to have a buffer to test audio and video before we hit record. I'm not content with the flow for creating a hangout on air (there's no option to create one for the future and grab the hangout url for it until you start it, which kind of defeats the purpose in my mind), so if you have a better process in mind, I'm happy to try it out.

**Comment by donaldali** [comment]
@gkop and I were just thinking about adding status messages for when a hangout will be available or if there will be none.
Maybe when I give teach a couple of lessons, I'll have something to contribute about the process.
