### ISSUE TITLE
twitter message too long causes a 500 error

### ISSUE THREAD

**Issue by btaitelb** [rails-school/school#173]
When I clicked to notify subscribers on https://www.railsschool.org/l/emulate-a-simple-unix-shell-in-ruby, I got a 500 error ("Something "Went Wrong") and had to look through the logs to see that it was a postgres error coming back from the database (field only allows 140 characters).

What's a better way to handle this?

**Comment by gkop** [comment]
I think if you add an activerecord validation that mirrors the database column max size, that should fix the 500.
