### ISSUE TITLE
Can't see poll results after refreshing page.

### ISSUE THREAD

**Issue by powersjcb** [rails-school/school#188]
I'll try to get motivated to add a view for this.

**Comment by roarkm** [comment]
Submitted pull request; ci build failed some tests that were unrelated to my changes (tests fail on master branch as well).

**Comment by gkop** [comment]
Are you sure @roarkm ? https://circleci.com/gh/rails-school/school/tree/master

**Comment by roarkm** [comment]
I updated the tests affected by my changes and rebased the branch.

*Note* - I'm still seeing two failed tests on the master branch on my machine; looks like they're Capybara::Poltergeist::JavascriptErrors in tests
/spec/acceptance/lessons_spec.rb:167  &  /spec/acceptance/lessons_spec.rb:192

They were the first failed tests I saw on both "master" and "polls" branches so I assumed my changes were orthogonal to the failures.

**Comment by gkop** [comment]
Cool, thanks Michael. I have merged and deployed. I think that closes this issue.
