### ISSUE TITLE
Etherpad Whiteboard is broken

### ISSUE THREAD

**Issue by cdale77** [rails-school/school#196]
Console is showing this error:
Refused to display 'https://pad.railsschool.org/p/rails-school-lesson-293?userName=Brad' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.
ping:1 Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

**Comment by cdale77** [comment]
This is probably because our etherpad host is down, not an actual problem with this site.

**Comment by btaitelb** [comment]
It should be fixed now. For some reason, the etherpad-lite upstart script was failing due to a missing or outdated version of `curl`.
